### PR TITLE
add possibility to use custom SessionManager with async 'get' method

### PR DESCRIPTION
**Pull request by nastasi**
This PR allow to use `aiohttp_security.authorized_userid` inside an optionally async get method of a custom SessionManager.
Currently tests are missing because I need some hint about how to proceed.

### CODE REVIEW

**Comment by asvetlov** [comment]
Hmm, looks really ugly.
Maybe break backward compatibility and make manager asynchronous?
Who implement own managers BTW?

**Comment by asvetlov** [comment]
I think making session manager asynchronous is ok.
@fafhrd91

**Comment by fafhrd91** [comment]
I don’t think i’ll be able to do sockjs development anytime soon. Best would be if anyone agrees to step in as a maintainer of the project

**Comment by asvetlov** [comment]
> Best would be if anyone agrees to step in as a maintainer of the project

Looks like I should take this burden.

**Comment by fafhrd91** [comment]
I am working on sockjs implementation for rust language. I’ll share my design decisions around async sessions mamagement

**Comment by nastasi** [comment]
@asvetlov after your comments I just moved SessionManager "get" method from sync to async, adjusting test accordingly. Token in your hands now.

**Comment by nastasi-oq** [comment]
@asvetlov I found a way to avoid changes on the sockjs directly, extending original classes.

**Comment by nastasi** [comment]
Here the code to avoid sockjs changes: https://github.com/nastasi/ao-enjoy/tree/v0.2.0
Could you release a new 0.6.1 version with the fix for IFRAME_HTML (https://github.com/aio-libs/sockjs/commit/21902d6573962c75384df702e06b7458210e5aaf), so I'm not forced to use git version.
Thank you.

**Pull request closed without merging**
