### PR TITLE
Fixed many errors. The code is not perfect, but at least it was working as it should.

### PR DESCRIPTION
**Pull request by Cykooz**

### CODE REVIEW

**Comment by fafhrd91** [comment]
looks good. 
did you test new changes with `sockjs-protocol`?

**Comment by fafhrd91** [comment]
also i do not like `500`.

**Comment by fafhrd91** [comment]
leave 500 for now.

**Comment by Cykooz** [comment]
Yes, I test new changes with `sockjs-protocol`. But this test not so good. They not passed this SockJS-node. But I corrected them as best he could, and now they pass.

**Comment by fafhrd91** [comment]
what did you change? it passes for me, i just disabled hixie76 tests.

**Comment by Cykooz** [comment]
Yes, I disabled the protocol tests for hixie76. Also I did small fix in the `verify_cors()` function. I added a substring `/**/` in some assertions. After all changes this tests should pass with this implementation.

**Comment by fafhrd91** [comment]
ok, i sent you invitation to sockjs-commiters team. accept it and then commit

**Comment by fafhrd91** [comment]
also add yourself to contributors

**Comment by Cykooz** [comment]
Nikolay, can you make the new release of **sockjs** and submit it to pypi.python.org?

**Comment by fafhrd91** [comment]
what is your pypi username?

**Comment by Cykooz** [comment]
Cykooz

**Comment by fafhrd91** [comment]
could you make release yourself?

**Comment by Cykooz** [comment]
Yes, I can. Thank you.

**Pull request merged**
